# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Alexandre Rousseau
email: alexandre@rsseau.fr
description: Mon Portfolio
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://rsseau.fr" # the base hostname & protocol for your site, e.g. http://example.com
github_username: madeindjs

permalink: /blog/:title

# Build settings
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge
  auto_ids: true
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-mermaid
  - jekyll-paginate
  - jekyll-multiple-languages-plugin
  - jekyll-toc

tag_page_layout: tag
tag_page_dir: tag

paginate: 10
paginate_path: "/blog/page/:num/"

languages: [fr, en]
exclude_from_localizations: [js, img, css]

defaults:
  - scope:
      path: ""
    values:
      toc: true

toc:
  max_level: 2

mermaid:
  src: https://cdnjs.cloudflare.com/ajax/libs/mermaid/7.1.2/mermaid.min.js

include:
  - .well-known
  - favicon.ico

sass:
  sass_dir: _sass
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
